### ISSUE TITLE
Glacier: Multipart Treehashes

### ISSUE THREAD

**Issue by purohit** [rdwilliamson/aws#11]
Hi,

Thanks for this great library. I'm trying to upload some massive (TB++) files to Glacier, and I noticed that completing the multipart upload requires a TreeHash. I don't want to re-read all the parts and calculate a TreeHash from that, or compute another TreeHash every part, since UploadMultipart already does this.

Is the recommended method to upload all the parts, call ListMultipartParts, go through the resulting []MultipartPart, self-compute the resulting TreeHash, and then call CompleteMultipart?

If so, shall I write a function for TreeHash that can compute the full TreeHash for a multipart upload given the treehash of all of its parts, as described here: http://docs.aws.amazon.com/amazonglacier/latest/dev/checksum-calculations.html

Thanks in advance.

**Comment by rdwilliamson** [comment]
Yes the method you described of calling ListMultipartParts and going through the results should work. I did a quick test uploading a few parts and then used them and the remainder of the file to compute the tree hash. It gave me the same result as computing the tree hash completely and directly from the file. I haven't done anything more thorough, such as seeing if Amazon actually excepts the results.

Rough outline of the code (no error checking and assumes the results of ListMultipartParts are in order):
```
// New method.
func (th *TreeHash) Add(hash [sha256.Size]byte) {
	th.nodes = append(th.nodes, treeHashNode{hash: hash})
}

// Building tree hash from parts.
parts, _ := connection.ListMultipartParts(Vault, UploadId, "", 0)
th := glacier.NewTreeHash()
for _, v := range parts.Parts {
    var bytes [sha256.Size]byte
    hex.Decode(bytes[:], []byte(v.SHA256TreeHash))
    th.Add(bytes)
}
th.Close()
fmt.Println(th.TreeHash)
```

**Comment by purohit** [comment]
Awesome! It works, and I have been able to write tests that verify this method of uploading archives and completing multiparts works. I'm not sure how useful they are to add to the codebase since they require an AWS account, but if you would like them I can commit them. At the very least, I'd like to add the Add function you wrote and a comment on CompleteMultipart that I stumbled on to the codebase.

**Comment by rdwilliamson** [comment]
Thanks for the contribution. With the addition of the MultiTreeHasher I'm considering this issue closed.
