### ISSUE TITLE
ListMultipartParts adds parameters to header instead of URL string

### ISSUE THREAD

**Issue by purohit** [rdwilliamson/aws#14]
The function ListMultipartParts adds the limit and marker parameters to the header, instead of the URL string. So, the request doesn't recognize them properly.

I fixed it and my tests ensure that pagination now works. I added the code to the pull request in #11. I suspect that ListMultipartUploads and any other GET requests suffer from the same problem, but I don't use them so I haven't fixed them (perhaps you can take a look this weekend). 

By the way, I have a pretty thorough multipart-uploading test suite I would like to add (takes 77s to run). It requires AWS credentials so I'll add them in a separate pull request, but I'm not sure what the best way to structure it would be (simply don't run the tests if the env variables aren't set?)

**Comment by rdwilliamson** [comment]
Thanks for fixing the header versus query string issue. I took a look at other methods, ListMultipartUploads gets it wrong too but ListJobs gets it right. Overall there isn't a consistent method to build the URL so I'm going to go through and probably clean them all up.

I'd love to add the tests. I'm not sure of a good way to structure it either. I often do small changes, test, repeat, and I wouldn't want them running every time. An environment variable seems okay. My only preference would have the tests disabled by default.

**Comment by rdwilliamson** [comment]
I added a parameter type (basically a wrapper around url.Values) in bc3edc23cfb61d8883df280355754057c58059fd and used it to build up parameters in a consistent manner everywhere.

**Comment by purohit** [comment]
Awesome, thanks!

2015-03-20 18:37 GMT-07:00 Robert Williamson <notifications@github.com>:
